#!/usr/bin/env python3
"""Turn the web board's station list into a flash-resident C++ table.

The web surface ships `web/public/stations.json` as `[name, crs]` pairs built
from the upstream CSV, and it contains only stations the provider can answer
for. The firmware needs the same list for two surfaces: the on-panel editor,
which names the code as you type it, and the setup portal, which searches by
name for boards with no touch panel. One dataset, generated once, so the two
cannot drift from each other or from the web board.

    scripts/generate_stations.py ../signalboarder/web/public/stations.json \
        > src/stations_data.h
"""

import json
import sys
from pathlib import Path


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2

    stations = json.loads(Path(sys.argv[1]).read_text())
    # Sort by CRS so the lookup can bisect, and reject anything that is not a
    # plain three-letter code: the panel draws A-Z only.
    entries = sorted(
        (crs.upper(), name)
        for name, crs in stations
        if len(crs) == 3 and crs.isalpha()
    )

    names: list[str] = []
    offsets: list[int] = []
    blob = 0
    for _, name in entries:
        offsets.append(blob)
        names.append(name)
        blob += len(name.encode("ascii", "replace")) + 1
    if blob > 0xFFFF:
        print("name blob exceeds a uint16 offset", file=sys.stderr)
        return 1

    out = sys.stdout
    out.write("#pragma once\n#include <stdint.h>\n\n")
    out.write(
        "// Generated by scripts/generate_stations.py from the web board's\n"
        "// public/stations.json. Do not edit by hand: regenerate both together\n"
        "// so the panel, the portal and the browser board name the same set.\n\n"
    )
    out.write("struct StationRecord {\n  char crs[3];\n  uint8_t reserved;\n"
              "  uint16_t nameOffset;\n};\n\n")
    out.write(f"inline constexpr uint16_t kStationCount = {len(entries)};\n\n")

    out.write("inline constexpr char kStationNames[] =\n")
    for name in names:
        escaped = name.encode("ascii", "replace").decode().replace("\\", "\\\\").replace('"', '\\"')
        out.write(f'    "{escaped}\\0"\n')
    out.write("    ;\n\n")

    out.write("inline constexpr StationRecord kStations[] = {\n")
    for (crs, _), offset in zip(entries, offsets):
        out.write("    {{'%s', '%s', '%s'}, 0, %d},\n" % (crs[0], crs[1], crs[2], offset))
    out.write("};\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
