#!/usr/bin/env python3
"""Embed the web board's Dot Matrix woff2 subsets for the board's own page.

The page the board serves has to look like the board. Linking the web host's
fonts would mean the page only looks right when the viewer has internet, which
is exactly the dependency this device is built to avoid, and the two cuts come
to ten kilobytes. So they live in flash beside the station list.

    scripts/generate_web_font.py ../signalboarder/web/public/fonts > src/web_font.h
"""

import sys
from pathlib import Path

FACES = [
    ("kDotMatrixRegular", "dot-matrix-regular.woff2"),
    ("kDotMatrixBold", "dot-matrix-bold.woff2"),
]


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    directory = Path(sys.argv[1])

    out = sys.stdout
    out.write("#pragma once\n#include <stdint.h>\n\n")
    out.write(
        "// Generated by scripts/generate_web_font.py from the web board's\n"
        "// public/fonts. Daniel Hart's Dot Matrix Typeface, subset, under the\n"
        "// SIL Open Font License. Keep public/fonts/README.txt with these bytes:\n"
        "// the licence requires that notice to travel with the files.\n\n"
    )
    for name, filename in FACES:
        data = (directory / filename).read_bytes()
        out.write(f"// {filename}, {len(data)} bytes\n")
        out.write(f"inline constexpr uint32_t {name}Length = {len(data)};\n")
        out.write(f"inline constexpr uint8_t {name}[] = {{\n")
        for start in range(0, len(data), 16):
            row = ", ".join(f"0x{byte:02x}" for byte in data[start:start + 16])
            out.write(f"    {row},\n")
        out.write("};\n\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
